Add invalidate existing email auth parameter
tkhq/sdk pull request #312
Opened 2024-07-15 21:46 UTC by zkharit

## Summary & Motivation
Add new parameter for invalidating previously issued email authentication tokens
Add parameter to email auth example
## How I Tested These Changes

## Did you add a changeset?

If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the type of [semver change (major.minor.patch)](https://semver.org/) (which you should set).

These changes will be used at release time to determine what packages to publish and how to bump their version. For more context see [this comment](https://github.com/tkhq/sdk/pull/67#issuecomment-1568838440).

2024-07-15 21:51 UTC, andrewkmin approved these changes
🔥 ready to merge once the next release is through!

2024-07-15 21:51 UTC, andrewkmin commented on examples/email-auth/src/pages/index.module.css
> +.input_checkbox {
👨‍🍳💋

2024-07-19 15:32 UTC, moe-dev requested changes
Needs default versioning for email auth added to codegen + running codegen script to update the clients for sdk browser/server. Otherwise LGTM!

2024-07-19 17:06 UTC, moe-dev approved these changes

2024-07-19 17:10 UTC, merged